batch_size: 32
data_dir: data
pre_slicing_transform:
  - class_path: tonic.transforms.CropTime
    init_args:
      max: 1_500_000
  - class_path: tonic.transforms.Downsample
    init_args:
      time_factor: 1.0
      spatial_factor: 0.5
slicer:
  class_path: tonic.slicers.SliceByTime
  init_args:
    time_window: 250_000
post_slicing_transform:
  - class_path: tonic.transforms.ToFrame
    init_args:
      sensor_size: [64, 64, 2]
      time_window: 5000
      include_incomplete: true
  - class_path: vision_team.augmentations.frame_based_augmentations.ToFloat
# augmentation:
#   - class_path: vision_team.augmentations.frame_based_augmentations.ToTensor
#   - class_path: torchvision.transforms.RandomPerspective
#     init_args:
#       distortion_scale: 0.5
#       p: 0.5
#   - class_path: torchvision.transforms.RandomErasing
#     init_args:
#       p: 0.5
#       scale: [0.02, 0.2]
cache_path: cache/raster
metadata_path: metadata/raster
num_workers: 4
